/**
 * `@tg/core/api` — HTTP clients, one file per domain, all on the canonical
 * `/api/chats/*` dialect via the shared injected-fetch `ApiClient`.
 *
 */
export * from './http'
export * from './config'
export * from './auth'
export * from './chats'
export * from './messages'
export * from './search'
export * from './drafts'
export * from './privacy'
export * from './twoFactor'
export * from './polls'
export * from './customEmoji'
export * from './deviceSessions'
export * from './stickers'
export * from './chatAdmin'
export * from './slowMode'
export * from './publicHandles'
export * from './favorites'
export * from './contacts'
export * from './folders'
export * from './discussion'
export * from './topics'
export * from './channels'
export * from './voice'
export * from './scheduled'
export * from './gifs'
export * from './inviteLinks'
