use std::{env, fmt::Write as _, fs, path::Path, path::PathBuf, process::Command};

/// `src/web.rs` embeds `sw.js` unconditionally, but the service worker was emitted by a
/// plugin in the old Vue `vite.config.ts` and precached that client's asset URLs. Serving it
/// now would pin browsers to bundles that no longer exist, so the React client ships a worker
/// that drops every cache and unregisters itself. Replaced automatically once `packages/web`
/// emits its own `sw.js`.
const RETIRED_SERVICE_WORKER: &str = r#"// Generated by build.rs. The React client has no service worker yet; this one exists only to
// retire the previous Vue client's precaching worker instead of leaving it in control.
self.addEventListener('install', () => {
  self.skipWaiting()
})
self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        await caches.delete(key)
      }
      await self.registration.unregister()
    })(),
  )
})
"#;

fn main() {
    for path in [
        // A custom rerun-if-changed list REPLACES cargo's default dirtiness rules, so without
        // these two entries a migration-only change never rebuilds the crate — and with the
        // shared build directory, a test binary can link a lib whose sqlx::migrate! embedded
        // a STALE migration set (measured by TG-008: applied 64/53 vs on-disk 65/54).
        "migrations",
        "migrations-postgres",
        "package.json",
        "bun.lock",
        "tsconfig.base.json",
        "packages/core/package.json",
        "packages/core/tsconfig.json",
        "packages/core/src",
        "packages/ui/package.json",
        "packages/ui/tsconfig.json",
        "packages/ui/src",
        "packages/web/package.json",
        "packages/web/tsconfig.json",
        "packages/web/vite.config.ts",
        "packages/web/index.html",
        "packages/web/src",
        "packages/web/public",
    ] {
        println!("cargo:rerun-if-changed={path}");
    }
    // bun puts workspace binaries in the member's own `node_modules/.bin`, not the root one.
    if !Path::new("packages/web/node_modules/.bin/vite").exists() {
        // cwd is the crate root, which is also the bun workspace root.
        let install = Command::new("bun")
            .args(["install", "--frozen-lockfile"])
            .status()
            .expect("run Bun; install Bun before running Cargo");
        assert!(install.success(), "Bun dependency installation failed");
    }

    let output_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set")).join("web");
    // `@tg/web`'s `build` is `tsc --noEmit && vite build`; bun appends these flags to the end
    // of that string, so they reach `vite build` and override `vite.config.ts`'s `outDir`.
    let status = Command::new("bun")
        .args(["run", "build", "--", "--outDir"])
        .arg(&output_dir)
        .arg("--emptyOutDir")
        .current_dir("packages/web")
        .status()
        .expect("run Bun; install Bun and run `bun install`");

    assert!(status.success(), "React web build failed");
    stage_service_worker(&output_dir);
    generate_asset_manifest(&output_dir);
}

/// `packages/web/public/` (copied by vite) supplies every file `src/web.rs` embeds except the
/// service worker, which the React client does not emit yet.
fn stage_service_worker(output_dir: &Path) {
    let service_worker = output_dir.join("sw.js");
    if !service_worker.exists() {
        fs::write(&service_worker, RETIRED_SERVICE_WORKER).expect("write retired service worker");
    }
}

fn generate_asset_manifest(output_dir: &Path) {
    let asset_dir = output_dir.join("assets");
    // Keys are paths relative to `assets/`, because `src/lib.rs` routes `/assets/*path` and
    // `web::bundled_asset` matches the captured remainder against these keys verbatim.
    let mut names = Vec::new();
    collect_asset_names(&asset_dir, &asset_dir, &mut names);
    names.sort();

    let mut source = String::from("const GENERATED_ASSETS: &[(&str, &str, &[u8])] = &[\n");
    for name in names {
        let content_type = content_type(Path::new(&name));
        writeln!(
            source,
            "    ({name:?}, {content_type:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/web/assets/{name}\"))),"
        )
        .expect("write asset manifest entry");
    }
    source.push_str("];\n");
    fs::write(
        output_dir
            .parent()
            .expect("web build output has a parent")
            .join("web_assets.rs"),
        source,
    )
    .expect("write web asset manifest");
}

fn collect_asset_names(root: &Path, directory: &Path, names: &mut Vec<String>) {
    for entry in fs::read_dir(directory).expect("read built web assets") {
        let path = entry.expect("read web asset entry").path();
        if path.is_dir() {
            collect_asset_names(root, &path, names);
        } else {
            names.push(
                path.strip_prefix(root)
                    .expect("asset is below the assets directory")
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
}

fn content_type(path: &Path) -> &'static str {
    match path.extension().and_then(|value| value.to_str()) {
        Some("css") => "text/css; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg" | "jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("webp") => "image/webp",
        Some("ico") => "image/x-icon",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("mp4") => "video/mp4",
        Some("webm") => "video/webm",
        _ => "application/octet-stream",
    }
}
