/**
 * The pages the shell itself plugs in (TG-110): 我的账号 and 设备 (built here), and the
 * merged M5 pages the lead mounts under 隐私与安全 — TG-505's `PrivacySettingsPage` and
 * TG-506's `TwoFactorSettings`. Every component is lazy, so none of them weighs on the boot
 * bundle; this module itself is imported by the (lazy) panel.
 *
 * Other M5 tasks do NOT edit this file: they call `registerSettingsPage` from their own
 * `register.ts` (see `settingsRegistry.ts`).
 */
import { createElement, lazy } from 'react'
import { SettingsIcon } from './settingsIcons'
import { registerSettingsPage, type SettingsPageProps } from './settingsRegistry'

const AccountPage = lazy(() => import('./pages/AccountPage'))
const DevicesPage = lazy(() => import('./pages/DevicesPage'))
const PrivacyPage = lazy(async () => {
  const { PrivacySettingsPage } = await import('../privacy')
  return { default: ({ onBack }: SettingsPageProps) => createElement(PrivacySettingsPage, { onBack }) }
})
const TwoFactorPage = lazy(async () => {
  const { TwoFactorSettings } = await import('../security')
  return { default: () => createElement(TwoFactorSettings) }
})

registerSettingsPage({
  id: 'account.profile',
  section: 'account',
  title: '我的账号',
  component: AccountPage,
  order: 10,
})
registerSettingsPage({ id: 'devices.sessions', section: 'devices', title: '设备', component: DevicesPage, order: 10 })
registerSettingsPage({
  id: 'privacy.rules',
  section: 'privacy',
  title: '隐私',
  icon: createElement(SettingsIcon, { name: 'privacy' }),
  component: PrivacyPage,
  order: 10,
  ownsHeader: true,
})
registerSettingsPage({
  id: 'privacy.two-factor',
  section: 'privacy',
  title: '两步验证',
  icon: createElement(SettingsIcon, { name: 'security' }),
  component: TwoFactorPage,
  order: 20,
})
