ALTER TABLE rooms ADD COLUMN avatar_emoji TEXT NOT NULL DEFAULT '';
ALTER TABLE rooms ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE room_memberships ADD COLUMN nickname TEXT NOT NULL DEFAULT '';
