/**
 * `@tg/core/domain` — pure business logic, one concern per file. No platform access, no
 * transport; anything platform-shaped arrives as an injected interface from
 * `types/platform.ts`.
 */
export * from './messageView'
export * from './calculator'
export * from './markdown'
export * from './chatOptimistic'
export * from './chatIncoming'
export * from './messageReactions'
export * from './messageMotion'
export * from './messageViewportPolicy'
export * from './attachmentUploadProgress'
export * from './fileHash'
export * from './avatarColor'
export * from './randomUuid'
export * from './messageDeepLink'
export * from './searchPattern'
export * from './textFrameBatch'
export * from './draftSync'
export * from './typingSummary'
export * from './lastSeen'
export * from './chatActionSender'
export * from './composerMode'
export * from './mentionMatch'
export * from './textFormatting'
export * from './pendingAttachments'
export * from './messageViewportLayout'
export * from './messageViewportWindow'
export * from './tgs'
export * from './messageEntities'
export * from './albumLayout'
export * from './autoDownload'
export * from './chatFolders'
